// words are written one by one.

var NumberOfWords = 200

var words = new BuildArray(NumberOfWords)

words[1] = "begrüßen > selamlamak"
words[2] = "buchstabieren > harf harf söylemek"
words[3] = "der Familienname > soyad,soyisim"
words[4] = "Hạllo! > Merhaba!"
words[5] = "die Herkunf > kök"
words[6] = "das Lạnd > ülke"
words[7] = "das Lẹrnziel > öğrenme amacı"
words[8] = "der Name > isim"
words[9] = "die Sprache > dil"
words[10] = "sprẹchen > konuşmak"
words[11] = "die Stạdt > şehir"
words[12] = "über > üzeri, üzerine"
words[13] = "ụnd > ve"
words[14] = "verạbschieden > vedalaşmak"
words[15] = "der Vorname > ad,isim"
words[16] = "vorstellen > kendini tanıtmak"
words[17] = "das Pọlnisch > Lehçe"
words[18] = "das Rụssisch > Rusça"
words[19] = "die Kụrsliste > kurs listesi"
words[20] = "aus > den/dan"
words[21] = "fragen > sormak"
words[22] = "Guten Tag! > iyi günler!"
words[23] = "heißen > adı ... olmak"
words[24] = "kọmmen > gelmek"
words[25] = "der Kụrs > kurs"

words[26] = "wie > nasıl"
words[27] = "woher > nereden"
words[28] = "der Deutschkurs > Almanca kursu"
words[29] = "der Dialog > diyalog"
words[30] = "ergänzen > tamamlamak"
words[31] = "Herr > bay"
words[32] = "hören > dinlemek"
words[33] = "in > de/da, te/ta"
words[34] = "die Sprache > dil"
words[35] = "der Kụrsleiter > kurs öğretmeni"
words[36] = "sein > olmak"
words[37] = "die Liste > liste"
words[38] = "machen > yapmak"
words[39] = "die Entschuldigung > özür"
words[40] = "die Frau > bayan"
words[41] = "mitlesen > beraber okumak"
words[42] = "der Tag > gün"
words[43] = "formell > resmi"
words[44] = "informell > gayri resmi"
words[45] = "oder > veya"
words[46] = "privat > özel"
words[47] = "der Akzent > vurgu"
words[48] = "die Aussprache > telaffuz"
words[49] = "die Melodie > melodi"
words[50] = "bitte > lütfen"

words[51] = "nachsprechen > dinleyip tekrar etmek"
words[52] = "auch > de/da, te/ta"
words[53] = "üben > alıştırma yapmak"
words[54] = "ạnkreuzen > çarpı koymak"
words[55] = "einmal > bir defa"
words[56] = "Guten Abend! > İyi akşamlar!"
words[57] = "nọch einmal > bir defa daha"
words[58] = "ọrdnen > sıraya koymak"
words[59] = "schreiben > yazmak"
words[60] = "spielen > oynamak"
words[61] = "der Aussagesatz > bildirme cümlesi"
words[62] = "das Beispiel > örnek"
words[63] = "laut > sesli, yüksek sesle"
words[64] = "lesen > okumak"
words[65] = "das Vẹrb > fil"
words[66] = "der Sạtz > cümle"
words[67] = "der Stẹckbrief > yakalama müzekkeresi"
words[68] = "das Chinesisch > Çince"
words[69] = "das Ẹnglisch > İngilizce"
words[70] = "das Französisch > Fransızca"
words[71] = "das Koreanisch > Korece"
words[72] = "das Pẹrsisch > Farsça"
words[73] = "raten > tahmin etmek"
words[74] = "das Spanisch > İspanyolca"
words[75] = "das Türkisch > Türkçe"

words[76] = "das Ukrainisch > Ukraynaca"
words[77] = "wạs > ne"
words[78] = "wer > kim"
words[79] = "wohnen > (bir şehirde) oturmak"
words[80] = "zuordnen > eşleştirmek"
words[81] = "kontrollieren > kontrol etmek"
words[82] = "genau > tam"
words[83] = "liegen > bulunmak"
words[84] = "das Portugiesisch > Portekizce"
words[85] = "das Slowakisch > Slovakça"
words[86] = "wo > nerede"
words[87] = "ạnder > diğer"
words[88] = "das Lẹrnplakat > öğrenme afişi"
words[89] = "sạmmeln > toplamak"
words[90] = "die Vẹrbform > fiil şekli"
words[91] = "der Nạchbar > komşu"
words[92] = "das Alphabet > alfabe"
words[93] = "lẹrnen > öğrenmek"
words[94] = "mịt > ile"
words[95] = "der Rhythmus > ritm"
words[96] = "nein > hayır"
words[97] = "die Person > şahıs"
words[98] = "die Leute > kişiler"
words[99] = "das Deutsch > Almanca"
words[100] = "verstehen > anlamak"

words[101] = "der Automechaniker > oto tamircisi "
words[102] = "der Beruf > meslek "
words[103] = "der Deutschlehrer > Almanca öğretmeni "
words[104] = "die Information > bilgi "
words[105] = "der Sekretär > sekreter "
words[106] = "der Wohnort > ikamet yeri "
words[107] = "der Ạlltag > gündelik hayat "
words[108] = "auf > de/da "
words[109] = "Auf Wiedersehen! > Görüşmek üzere! "
words[110] = "der Blịck > bakış "
words[111] = "Tschüs! > Hoşçakal! "
words[112] = "der Artịkel > tanımlık "
words[113] = "die Ẹndung > ek,takı "
words[114] = "das Ẹstnisch > Estonyaca "
words[115] = "haben > sahip olmak "
words[116] = "ọft > sık"
words[117] = "das Schwedisch > İsveççe "
words[118] = "der Sprachenname > dil adı "
words[119] = "die Grammạtik > dilbilgisi "
words[120] = "das Fragewort > soru kelimesi "
words[121] = "fạllen > düşmek "
words[122] = "mạn > insan "
words[123] = "das Sạtzende > cümle sonu "
words[124] = "die Sạtzmelodie > cümle melodisi"
words[125] = "steigen > yükselmek"

words[126] = "die Antwort > cevap"
words[127] = "antworten > cevap vermek"
words[128] = "die Frage > soru"
words[129] = "die Adresse > adres"
words[130] = "danke > teşekkür ederim"
words[131] = "gut, besser > iyi "
words[132] = "jemand > biri"
words[133] = "der Kaffee > kahve"
words[134] = "möchten > istemek"
words[135] = "nehmen > almak"
words[136] = "sagen > söylemek"
words[137] = "super > süper"
words[138] = "der Tee > çay"
words[139] = "die Telefonnummer > telefon numarası"
words[140] = "trinken > içmek"
words[141] = "vọn > den/dan"
words[142] = "was > ne"
words[143] = "das Wasser > su"
words[144] = "wie  > nasıl"
words[145] = "Wie geht's? > Nasılsınız?"
words[146] = "zählen > saymak"
words[147] = "zeichnen > çizmek"
words[148] = "ganz > tam,bütün"
words[149] = "ansehen > bakmak"
words[150] = "die Szene > sahne"

words[151] = "die Milch > süt"
words[152] = "schwarz > siyah"
words[153] = "viel > çok"
words[154] = "der Zucker > şeker "
words[155] = "gehen > gitmek"
words[156] = "gern > memnuniyetle"
words[157] = "ja > evet"
words[158] = "nur > sadece"
words[159] = "die Ja/Nein-Frage > Evet/Hayır sorusu "
words[160] = "an > de/da"
words[161] = "kennen > bilmek"
words[162] = "die Tafel > karatahta"
words[163] = "der Lehrer > öğretmen"
words[164] = "der Orangensaft > portakal suyu"
words[165] = "vorlesen > sesli okumak"
words[166] = "die Cafeteria > kafeterya"
words[167] = "rịchtig > doğru"
words[168] = "zu > bir yerde"
words[169] = "dann > daha sonra"
words[170] = "frei > serbest"
words[171] = "hier > burada"
words[172] = "klar > elbette"
words[173] = "das Mineralwasser > maden suyu"
words[174] = "natürlich > doğal,tabii"
words[175] = "toll > şahane"

words[176] = "das Personalpronomen > şahıs zamiri"
words[177] = "markieren > işaretlemek"
words[178] = "als > olarak"
words[179] = "arbeiten > çalışmak"
words[180] = "der Espresso > espresso"
words[181] = "selbst > kendi"
words[182] = "die Übung > alıştırma"
words[183] = "das Kärtchen > küçük kart"
words[184] = "bis > kadar"
words[185] = "notieren > not etmek"
words[186] = "die Zahl > sayı"
words[187] = "mitsprechen > birlikte söylemek"
words[188] = "das Handy > cep telefonu"
words[189] = "die Handynummer > cep numarası"
words[190] = "die Vorwahl > alan kodu"
words[191] = "die E-mail > e-posta"
words[192] = "die E-mail Adresse > e-mail adresi"
words[193] = "die Postleitzahl > posta kodu"
words[194] = "das Telefon > telefon"
words[195] = "dauern > sürmek"
words[196] = "jetzt > şimdi"
words[197] = "müde > yorgun"
words[198] = "noch > daha"
words[199] = "schon > halihazırda"
words[200] = "die Stunde > saat"


function BuildArray(size){
this.length = size
for (var i = 1; i <= size; i++){
this[i] = null}
return this
}

function PickRandomWord(frm) {
// Generate a random number between 1 and NumberOfWords
var rnd = Math.ceil(Math.random() * NumberOfWords)

// Display the word inside the text box
frm.WordBox.value = words[rnd]
}
